apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 897722705551.dkr.ecr.ca-central-1.amazonaws.com/springboot-ecr:v1
          ports:
            - containerPort: 8080

